#!/bin/sh
# One-shot installer for ci-hub on Debian 12 (works in unprivileged LXC).
#
#   curl -fsSL https://raw.githubusercontent.com/kuchmenko/ci-hub/main/install.sh | sh
#
# Installs PostgreSQL 15, OpenJDK 17, SonarQube Community Build natively
# (no Docker). SonarQube becomes available at http://<host>:9000.
#
# Override variables via env:
#   SONAR_VERSION   default 25.1.0.102122
#   INSTALL_DIR     default /opt/ci-hub
#   SONAR_HOME      default /opt/sonarqube

set -eu

INSTALL_DIR="${INSTALL_DIR:-/opt/ci-hub}"
SONAR_HOME="${SONAR_HOME:-/opt/sonarqube}"
SONAR_VERSION="${SONAR_VERSION:-25.1.0.102122}"

log()  { printf '[install] %s\n' "$*"; }
warn() { printf '[install] WARN: %s\n' "$*" >&2; }
die()  { printf '[install] ERROR: %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root"

[ -f /etc/os-release ] || die "/etc/os-release not found"
# shellcheck source=/dev/null
. /etc/os-release
if [ "${ID:-}" != "debian" ]; then
    warn "tested on Debian 12 (bookworm); detected ${ID:-?} ${VERSION_CODENAME:-?}"
fi

# ---- vm.max_map_count check (must be set on the Proxmox HOST in LXC) ----

mmc="$(sysctl -n vm.max_map_count 2>/dev/null || echo 0)"
if [ "$mmc" -lt 262144 ]; then
    warn "vm.max_map_count=$mmc, but SonarQube's Elasticsearch needs >= 262144."
    warn "If this is an LXC: set on the PROXMOX HOST (not in this container):"
    warn "  echo 'vm.max_map_count=262144' > /etc/sysctl.d/99-sonarqube.conf"
    warn "  sysctl --system"
    warn "On a VM, the script will set it inside automatically."
    if [ -w /proc/sys/vm/max_map_count ]; then
        log "Writable here, setting persistent..."
        printf 'vm.max_map_count=262144\n' > /etc/sysctl.d/99-sonarqube.conf
        sysctl -p /etc/sysctl.d/99-sonarqube.conf >/dev/null
    fi
fi

# ---- Install system packages ----

log "Installing system packages..."
apt-get update -qq
apt-get install -y -qq \
    postgresql-15 \
    openjdk-17-jre-headless \
    unzip wget curl ca-certificates

# ---- Generate / load .env ----

mkdir -p "$INSTALL_DIR"
if [ ! -f "$INSTALL_DIR/.env" ]; then
    log "Generating .env with random Postgres password..."
    pg_pass="$(head -c 24 /dev/urandom | base64 | tr -d '/=+')"
    {
        printf '# Generated by install.sh on %s. Do not commit.\n' "$(date -Iseconds)"
        printf 'POSTGRES_PASSWORD=%s\n' "$pg_pass"
    } > "$INSTALL_DIR/.env"
    chmod 0600 "$INSTALL_DIR/.env"
fi
# shellcheck source=/dev/null
. "$INSTALL_DIR/.env"

# ---- Postgres setup (idempotent) ----

log "Configuring PostgreSQL..."
systemctl enable --now postgresql

if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='sonarqube'" | grep -q 1; then
    sudo -u postgres psql -c "CREATE USER sonarqube WITH PASSWORD '$POSTGRES_PASSWORD';"
fi
# Always sync password (in case .env changed)
sudo -u postgres psql -c "ALTER USER sonarqube WITH PASSWORD '$POSTGRES_PASSWORD';" >/dev/null

if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='sonarqube'" | grep -q 1; then
    sudo -u postgres psql -c "CREATE DATABASE sonarqube OWNER sonarqube;"
fi

# ---- Download and unpack SonarQube ----

if [ ! -d "$SONAR_HOME" ]; then
    log "Downloading SonarQube $SONAR_VERSION..."
    tmpzip="/tmp/sonarqube-${SONAR_VERSION}.zip"
    wget -q -O "$tmpzip" \
        "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-${SONAR_VERSION}.zip" \
        || die "failed to download SonarQube; try a different SONAR_VERSION"
    unzip -q "$tmpzip" -d /opt
    mv "/opt/sonarqube-${SONAR_VERSION}" "$SONAR_HOME"
    rm -f "$tmpzip"
fi

# ---- Create dedicated system user ----

if ! id sonarqube >/dev/null 2>&1; then
    useradd -r -s /bin/false -d "$SONAR_HOME" sonarqube
fi
chown -R sonarqube:sonarqube "$SONAR_HOME"

# ---- Configure sonar.properties ----

log "Writing $SONAR_HOME/conf/sonar.properties..."
cat > "$SONAR_HOME/conf/sonar.properties" <<EOF
sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonarqube
sonar.jdbc.username=sonarqube
sonar.jdbc.password=${POSTGRES_PASSWORD}
sonar.web.host=0.0.0.0
sonar.web.port=9000
EOF
chown sonarqube:sonarqube "$SONAR_HOME/conf/sonar.properties"
chmod 0640 "$SONAR_HOME/conf/sonar.properties"

# ---- systemd unit ----

log "Writing /etc/systemd/system/sonarqube.service..."
cat > /etc/systemd/system/sonarqube.service <<EOF
[Unit]
Description=SonarQube service
After=syslog.target network.target postgresql.service
Requires=postgresql.service

[Service]
Type=forking
ExecStart=${SONAR_HOME}/bin/linux-x86-64/sonar.sh start
ExecStop=${SONAR_HOME}/bin/linux-x86-64/sonar.sh stop
User=sonarqube
Group=sonarqube
Restart=on-failure
LimitNOFILE=131072
LimitNPROC=8192
TimeoutStartSec=5min

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable sonarqube
systemctl restart sonarqube

# ---- Wait for SonarQube to come up ----

log "Waiting for SonarQube to respond UP (typically 3-7 minutes)..."
deadline="$(( $(date +%s) + 600 ))"
ready=0
while :; do
    if curl -fsSL http://localhost:9000/api/system/status 2>/dev/null | grep -q '"status":"UP"'; then
        ready=1
        break
    fi
    if [ "$(date +%s)" -gt "$deadline" ]; then
        break
    fi
    sleep 10
done

vm_ip="$(hostname -I | awk '{print $1}')"

if [ "$ready" -eq 1 ]; then
    log "SonarQube is UP."
else
    log "SonarQube has not yet reported UP after 10 minutes."
    log "Check: journalctl -u sonarqube -n 100 --no-pager"
    log "       tail -f $SONAR_HOME/logs/web.log"
fi

cat <<EOF

[install] done.

SonarQube:     http://${vm_ip}:9000
First login:   admin / admin (rotate the password immediately)

Service:       systemctl status sonarqube
Logs:          journalctl -u sonarqube -e
Restart:       systemctl restart sonarqube

EOF
