#!/bin/sh
# One-shot installer for ci-hub on Debian 12.
#
#   curl -fsSL https://raw.githubusercontent.com/kuchmenko/ci-hub/main/install.sh | sudo sh
#
# Installs Docker, clones the repo, generates a random Postgres password,
# and brings up SonarQube. Access at http://<VM_IP>:9000 — first login is
# admin/admin; rotate the password immediately.

set -eu

INSTALL_DIR="${INSTALL_DIR:-/opt/ci-hub}"
BRANCH="${BRANCH:-main}"
REPO_URL="${REPO_URL:-https://github.com/kuchmenko/ci-hub.git}"

log() { printf '[install] %s\n' "$*"; }
die() { printf '[install] ERROR: %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root: pipe into 'sudo sh'"

[ -f /etc/os-release ] || die "/etc/os-release not found — cannot determine OS"
# shellcheck source=/dev/null
. /etc/os-release
if [ "${ID:-}" != "debian" ]; then
    log "WARNING: tested on Debian 12; detected ${ID:-?} ${VERSION_CODENAME:-?}"
fi

# ---- Docker CE + git ----

if ! command -v docker >/dev/null 2>&1; then
    log "Installing Docker CE..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg git
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    arch="$(dpkg --print-architecture)"
    codename="${VERSION_CODENAME:-bookworm}"
    printf 'deb [arch=%s signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian %s stable\n' \
        "$arch" "$codename" > /etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
        docker-buildx-plugin docker-compose-plugin
    systemctl enable --now docker
fi

if ! command -v git >/dev/null 2>&1; then
    apt-get install -y -qq git
fi

# ---- Elasticsearch kernel tunable (required by SonarQube) ----

current_mmc="$(sysctl -n vm.max_map_count)"
if [ "$current_mmc" -lt 262144 ]; then
    log "Setting vm.max_map_count=262144 (persistent)..."
    printf 'vm.max_map_count=262144\n' > /etc/sysctl.d/99-sonarqube.conf
    sysctl -p /etc/sysctl.d/99-sonarqube.conf >/dev/null
fi

# ---- Clone / update repo ----

if [ -d "$INSTALL_DIR/.git" ]; then
    log "Updating $INSTALL_DIR (branch: $BRANCH)..."
    git -C "$INSTALL_DIR" fetch --quiet origin "$BRANCH"
    git -C "$INSTALL_DIR" checkout --quiet "$BRANCH"
    git -C "$INSTALL_DIR" pull --ff-only --quiet origin "$BRANCH"
elif [ -e "$INSTALL_DIR" ]; then
    die "$INSTALL_DIR exists but is not a git repo"
else
    log "Cloning into $INSTALL_DIR..."
    git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# ---- First-run: generate .env with random PG password ----

if [ ! -f .env ]; then
    log "Generating .env with random Postgres password..."
    pg_pass="$(head -c 24 /dev/urandom | base64 | tr -d '/=+')"
    {
        printf '# Generated by install.sh on %s. Do not commit.\n' "$(date -Iseconds)"
        printf 'POSTGRES_PASSWORD=%s\n' "$pg_pass"
    } > .env
    chmod 0600 .env
fi

# ---- Bring up hub ----

log "Starting SonarQube + Postgres..."
docker compose -f compose.minimal.yml up -d

log "Waiting for SonarQube to become healthy (typically 3-7 minutes; on a"
log "small LXC the embedded Elasticsearch can take longer to settle)..."
deadline="$(( $(date +%s) + 600 ))"
healthy=0
while :; do
    if docker compose -f compose.minimal.yml ps | grep -q 'sonarqube.*(healthy)'; then
        healthy=1
        break
    fi
    if [ "$(date +%s)" -gt "$deadline" ]; then
        break
    fi
    sleep 10
done

vm_ip="$(hostname -I | awk '{print $1}')"

if [ "$healthy" -eq 1 ]; then
    log "SonarQube is healthy."
else
    log "SonarQube did not report healthy in 10 minutes. It may still be"
    log "starting; check status with:"
    log "  cd $INSTALL_DIR && docker compose -f compose.minimal.yml ps"
    log "  curl -fsSL http://${vm_ip}:9000/api/system/status"
fi

cat <<EOF

[install] done.

SonarQube:    http://${vm_ip}:9000
First login:  admin / admin  (rotate the password immediately)

Next steps in SonarQube UI:
  1. Rotate admin password
  2. Generate an analysis token (for CI runners)
  3. (optional) Configure quality gates

Runners + Trivy (Phase 4+):
  Add GITHUB_PAT=ghp_... to $INSTALL_DIR/.env, then:
    cd $INSTALL_DIR
    docker compose -f compose.yml up -d

EOF
